url: "https://bhavyasaggi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-hacker

show_downloads: false
google_analytics: "xxx"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/